import pandas as pd
df = pd.read_csv("dataset/vehicles.csv")
print(f"Records: {len(df)}")
print(f"Preco: R$ {df['preco'].min():.0f} - R$ {df['preco'].max():.0f}")
print(f"Preco medio: R$ {df['preco'].mean():.0f}")
print()
print("Por marca:")
print(df["marca"].value_counts().to_string())
print()
print("Por categoria:")
print(df["categoria"].value_counts().to_string())
print()
print("Exemplos:")
for _, r in df.head(15).iterrows():
    print(f"  {r['id']:3d}. {r['marca']:15s} {r['nome']:40s} {r['ano']} R$ {r['preco']:>7.0f}")
